//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditApplication.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int CreditId { get; set; }
        public int KindCreditId { get; set; }
        public int ClientId { get; set; }
        public decimal CreditSumm { get; set; }
        public System.DateTime DateOfIssue { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual KindCredit KindCredit { get; set; }
    }
}
